### ISSUE TITLE
Set default face to Roboto Flex

### ISSUE THREAD

**Issue by davelab6** [FontBureau/variable-type-tools#85]
Please set default face to Roboto Flex

Also please remove Roboto Delta

**Comment by davelab6** [comment]
And please add back Amstelvar Alpha

**Comment by davelab6** [comment]
Flex hasn't been updated in 10 months per https://github.com/TypeNetwork/variable-type-tools/tree/master/fonts :(

**Comment by graphicore** [comment]
I have deployed an updated version at Google App Engine: https://variable-type-tools.appspot.com/

However, we want to move to https://typetools.fontbureau.com and therefore some DNS records need to be set.

The first one is a `TXT` record with the value `google-site-verification=an6yXfxL6LPGaAoVnU5v5QcKBaoXkvsRs8-lMD31gaM` to verify we are the owner of the (sub-)domain.

@sannorozco did set it, but apparently the setting is not promoted by DNS, thus I'm stuck at this point. The appspot link above is working however.

To illustrate the issue, using `dig` for a DNS query I don't get the value:

```
$ dig typetools.fontbureau.com TXT

; <<>> DiG 9.16.25 <<>> typetools.fontbureau.com TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 7976
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;typetools.fontbureau.com.	IN	TXT

;; AUTHORITY SECTION:
fontbureau.com.		3176	IN	SOA	ns1.gandi.net. hostmaster.gandi.net. 1635803146 10800 3600 604800 10800

;; Query time: 32 msec
;; SERVER: 192.168.178.1#53(192.168.178.1)
;; WHEN: Thu Apr 14 08:35:00 CEST 2022
;; MSG SIZE  rcvd: 113
```

We also tried to set an `A` record to an IP, but it neither gets promoted, nor does it release the TXT record (which was my twisted hope):

```
$ dig typetools.fontbureau.com A

; <<>> DiG 9.16.25 <<>> typetools.fontbureau.com A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 29030
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;typetools.fontbureau.com.	IN	A

;; AUTHORITY SECTION:
fontbureau.com.		3052	IN	SOA	ns1.gandi.net. hostmaster.gandi.net. 1635803146 10800 3600 604800 10800

;; Query time: 4 msec
;; SERVER: 192.168.178.1#53(192.168.178.1)
;; WHEN: Thu Apr 14 08:37:04 CEST 2022
;; MSG SIZE  rcvd: 113
```

For comparison, here's the `dig` result for the `TXT` record of https://videoproof.graphicore.de which has the same setup on Google App Engine, see `ANSWER SECTION`:

```
$ dig videoproof.graphicore.de TXT

; <<>> DiG 9.16.25 <<>> videoproof.graphicore.de TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4409
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;videoproof.graphicore.de.	IN	TXT

;; ANSWER SECTION:
videoproof.graphicore.de. 3600	IN	TXT	"google-site-verification=0nj8Ag6E7sDSml6PFOB73jHCiJZ_1oOS5xtaOvLPSOQ"

;; Query time: 32 msec
;; SERVER: 192.168.178.1#53(192.168.178.1)
;; WHEN: Thu Apr 14 08:39:17 CEST 2022
;; MSG SIZE  rcvd: 134
```

**Comment by kenmcd** [comment]
> However, we want to move to https://typetools.fontbureau.com and therefore some DNS records need to be set.

Is this going to replace: https://typetools.typenetwork.com/

**Comment by dberlow** [comment]
That is the plan.

On Apr 14, 2022, at 9:54 PM, kenmcd ***@***.***> wrote:

﻿
However, we want to move to https://typetools.fontbureau.com and therefore some DNS records need to be set.

Is this going to replace: https://typetools.typenetwork.com/

**Comment by davelab6** [comment]
@graphicore please cut after `[` in the family dropdown :)

<img width="619" alt="Screen Shot 2022-04-28 at 11 38 49 AM" src="https://user-images.githubusercontent.com/261579/165814103-7dadb616-7d4d-44e7-ac5e-fb63e57932e6.png">

**Comment by sannorozco** [comment]
@davelab6 http://typetools.typenetwork.com/ now redirects to [https://variable-type-tools.appspot.com](https://variable-type-tools.appspot.com)

**Comment by graphicore** [comment]
Nothing left to do here as of https://github.com/FontBureau/videoproof/issues/30#issuecomment-1352989448 the curent state is OK.
